class FlightSearchPO {
  tabFlight = () => cy.get('#flightTab')
  lstMenu = () => cy.get('.searchengine-tab > ul > li')
  rbtnRoundTrip = () => cy.get('#rt')
  rbtnOneWay = () => cy.get('#ow')
  tfReturnDate = () => cy.get('#toDate')
  tfReturnFromCity = () => cy.get('#returnFroCity')
  tfReturnToCity = () => cy.get('#returnToCity')
  tfFromCity = () => cy.get('#froCity')
  tfToCity = () => cy.get('#toCity')
  lnkInfo = () => cy.get('.unaccompanied-minor > a')
  txtInfo = () => cy.get('#uncomMinor')
  menuAutoSuggest = () => cy.get('.ui-menu-item').children()
  ddlSelectAirline = () => cy.get('#select-air')
  btnSearch =   () => cy.contains('.search-btn', 'Search')
  ddlTraveler = () => cy.get('#traveller_info')
  tfPerson = () => cy.get('#person')
  btnDone = () => cy.get('#traveller_done')
  ddlCabinClass = () => cy.get('#cabin_btns')
  tfAdult = () => cy.get('#adult')
  tfChild = () => cy.get('#child')
  tfInfantLap = () => cy.get('#infant')
  tfInfantSeat = () => cy.get('#infantWs')
}

module.exports = new FlightSearchPO()
