class FlightSearchPO {
    tabFlight = () => cy.get('#flightTab')
    lstMenu = () => cy.get('.list-one > li')
    rbtnRoundTrip = () => cy.get('#rt')
    rbtnOneWay = () => cy.get('#ow')
    lnkAdvSearch = () => cy.get("[href='#advancedSearch']")
    tfReturnDate = () => cy.get('#returnDate')
    tfReturnFromCity = () => cy.get('#returnFroCity')
    tfReturnToCity = () => cy.get('#returnToCity')
    tfFromCity = () => cy.get('#froCity')
    tfToCity = () => cy.get('#toCity')
    lnkInfo = () => cy.get('#unAccompanied')
    txtInfo = () => cy.get('#unaccompaniedText')
    menuAutoSuggest = () => cy.get('.ui-menu-item').children()
    ddlSelectAirline = () => cy.get('#select-air')
    btnSearch = () => cy.contains('#search-btn-xxx', 'Search')
    ddlTraveler = () => cy.get('.travelerOpen .dropdown-menu')
    tfPerson = () => cy.get('#person')
    btnDone = () => cy.get('.travelerClose.btn')
    ddlCabinClass = () => cy.get('#cabinClass')
    tfAdult = () => cy.get('#adult')
    tfChild = () => cy.get('#child')
    tfInfantLap = () => cy.get('#infant')
    tfInfantSeat = () => cy.get('#infantWs')
}

module.exports = new FlightSearchPO()