name: CI

on:
  push:
    branches:
    - "*"
  # schedule:
  #   - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Remove json result files
        uses: JesseTG/rm@v1.0.2
        with:
          path: ./cypress/results/json

      - name: Install and run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: cypress-videos
      #     path: public/videos
        
      # - name: Copy test execution videos
      #   run: |
      #     mkdir public
      #     cp -r cypress/videos public/videos
      
      - name: Merge test results into one
        run: npm run report:merge
        
      - name: Generate HTML report
        run: npm run report:gen
        
      - name: Deploy report to GitHub pages
        if: github.actor != 'dependabot[bot]'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
